### ISSUE TITLE
request-sync -> sync-request

### ISSUE THREAD

**Issue by jkrems** [groupon-testium/webdriver-http-sync#25]
The readme of `request-sync` says it's deprecated.

See: https://www.npmjs.com/package/request-sync

(Also, testium currently does not install on io.js)

**Comment by EndangeredMassa** [comment]
@jkrems can you create a new issue for io.js support with the error log?

Yeah, let's look into using [sync-request](https://github.com/ForbesLindesay/sync-request) instead.

**Comment by jkrems** [comment]
The error log is basically just a bunch of C++ compiler errors when compiling the curl bindings. So pretty straight "native code that doesn't support the new v8 API".

**Comment by EndangeredMassa** [comment]
sync-request fails to install for me under linux. Looks like this is the cause: https://github.com/ForbesLindesay/thread-sleep/issues/2

**Comment by ForbesLindesay** [comment]
Are you sure it fails to install?  thread-sleep is an optional dependency, so it shouldn't give you any problems.  You will get lots error logs from npm, but they can be safely ignored.  sync-request will be better supported in the long run in any case, and is a much cleaner/more reliable design.

**Comment by EndangeredMassa** [comment]
Ah, I didn't notice it was an optional dependency. The latest version does install just fine for me on Linux, now.

I'm working on migrating from request-sync to sync-request.

**Comment by EndangeredMassa** [comment]
I'm getting an error from the ghostdriver in phantomjs when I link the changes to testium. [wip changes](https://github.com/groupon-testium/webdriver-http-sync/commit/b383731a2c6f89ca8b2b92c61d3fddfa4d13090b#diff-5b6270202e7b362597737840968ab7fcL33)

```
$ make test-integration
# Integration Tests #

  imgLoaded
->  POST http://127.0.0.1:51781/wd/hub/session {"json":"{\"desiredCapabilities\":{\"browserName\":\"phantomjs\",\"phantomjs.page.settings.resourceTimeout\":2500}}"}
<-  Missing Command Parameter - {"headers":{"Connection":"close","Host":"127.0.0.1:51781","accept-encoding":"gzip,deflate","content-length":"108","content-type":"application/json"},"httpVersion":"1.1","method":"POST","url":"/session","urlParsed":{"anchor":"","query":"","file":"session","directory":"/","path":"/session","relative":"/session","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/session","queryKey":{},"chunks":["session"]}}
    1) "before all" hook: Testium setup hook

  0 passing (387ms)
  1 failing

  1) imgLoaded "before all" hook: Testium setup hook:
     Uncaught Error: Failed to initialize WebDriver. Check the phantomjs.log.
Assertion failed: Failed to start WebDriver session.
Expected: undefined
Actually: 200
    at error (/home/smassa/source/webdriver-http-sync/node_modules/assertive/lib/assertive.js:365:12)
    at Object.assert.equal (/home/smassa/source/webdriver-http-sync/node_modules/assertive/lib/assertive.js:103:15)
    at module.exports (/home/smassa/source/webdriver-http-sync/lib/session.js:49:10)
    at new WebDriver (/home/smassa/source/webdriver-http-sync/lib/index.js:75:12)
    at createDriver (/home/smassa/source/testium/lib/testium.js:112:18)
    at createBrowser (/home/smassa/source/testium/lib/testium.js:123:86)
    at /home/smassa/source/testium/lib/testium.js:133:25
    at /home/smassa/source/testium/lib/processes/index.js:151:16
    at /home/smassa/source/testium/node_modules/async/lib/async.js:454:17
    at /home/smassa/source/testium/node_modules/async/lib/async.js:444:17
    at Array.forEach (native)
    at _each (/home/smassa/source/testium/node_modules/async/lib/async.js:46:24)
    at Object.taskComplete (/home/smassa/source/testium/node_modules/async/lib/async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
  
make: *** [test-integration] Error 1
```

And the selenium version:

```
$ make chrome
./cli.js --download-selenium
[testium] grabbing selenium standalone server 2.43.0
[testium] grabbing selenium chromedriver 2.14
make[1]: Entering directory `/home/smassa/source/testium'
# Integration Tests #

  imgLoaded
->  POST http://127.0.0.1:46547/wd/hub/session {"json":"{\"desiredCapabilities\":{\"browserName\":\"chrome\"}}","timeout":6000,"socketTimeout":2000}
<-  {"status":13,"sessionId":null,"value":{"message":"JSON command: \"{\\\"desiredCapabilities\\\":{\\\"browserName\\\":\\\"chrome\\\"}}\"\nBuild info: version: '2.43.0', revision: '597b76b', time: '2014-09-09 20:52:14'\nSystem info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-44-generic', java.version: '1.7.0_75'\nDriver info: driver.version: unknown","localizedMessage":"JSON command: \"{\\\"desiredCapabilities\\\":{\\\"browserName\\\":\\\"chrome\\\"}}\"\nBuild info: version: '2.43.0', revision: '597b76b', time: '2014-09-09 20:52:14'\nSystem info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-44-generic', java.version: '1.7.0_75'\nDriver info: driver.version: unknown","suppressed":[],"supportUrl":null,"systemInformation":"System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-44-generic', java.version: '1.7.0_75'","class":"org.openqa.selenium.remote.JsonException","additionalInformation":"\nDriver info: driver.version: unknown","hCode":1005251390,"stackTrace":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},"state":"unhandled error","class":"org.openqa.selenium.remote.Response","hCode":791226142}
    1) "before all" hook: Testium setup hook

  0 passing (7s)
  1 failing

  1) imgLoaded "before all" hook: Testium setup hook:
     Uncaught Error: Failed to initialize WebDriver. Check the selenium.log.
Assertion failed: Failed to start WebDriver session.
Expected: undefined
Actually: 200
    at error (/home/smassa/source/webdriver-http-sync/node_modules/assertive/lib/assertive.js:365:12)
    at Object.assert.equal (/home/smassa/source/webdriver-http-sync/node_modules/assertive/lib/assertive.js:103:15)
    at module.exports (/home/smassa/source/webdriver-http-sync/lib/session.js:49:10)
    at new WebDriver (/home/smassa/source/webdriver-http-sync/lib/index.js:75:12)
    at createDriver (/home/smassa/source/testium/lib/testium.js:112:18)
    at createBrowser (/home/smassa/source/testium/lib/testium.js:123:86)
    at /home/smassa/source/testium/lib/testium.js:133:25
    at /home/smassa/source/testium/lib/processes/index.js:151:16
    at /home/smassa/source/testium/node_modules/async/lib/async.js:454:17
    at /home/smassa/source/testium/node_modules/async/lib/async.js:444:17
    at Array.forEach (native)
    at _each (/home/smassa/source/testium/node_modules/async/lib/async.js:46:24)
    at Object.taskComplete (/home/smassa/source/testium/node_modules/async/lib/async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

make[1]: *** [test-integration] Error 1
make[1]: Leaving directory `/home/smassa/source/testium'
make: *** [chrome] Error 2
```

I imagine I'm not passing the post data properly, but I don't know what's wrong.

**Comment by jkrems** [comment]
I figured most of it out - with the exception of one thing: phantomjs/ghostdriver has case sensitive http header handling. Yes, seriously. This works:

```
curl -XPOST -H 'Content-Length: 51' -d '{"desiredCapabilities":{"browserName":"phantomjs"}}'  http://127.0.0.1:4499/session
```

This doesn't:

```
curl -XPOST -H 'content-length: 51' -d '{"desiredCapabilities":{"browserName":"phantomjs"}}'  http://127.0.0.1:4499/session
```

Unfortunately `sync-request` uses `then-request` that forces all headers to lowercase (for some reason). Will try to open a PR for `then-request` to use something like `caseless` instead.

**Comment by EndangeredMassa** [comment]
Ah! I was looking out for that, but didn't notice `then-request` was forcing them one way. Thanks!

**Comment by jkrems** [comment]
I'm not 100% sure what is yet (and didn't compare) but it looks like the speed is abysmal:

```
  webdriver-http-sync:request GET http://127.0.0.1:4499/session/c884f140-b224-11e4-a842-255fd52ba2bf/title +16s null
    ✓ can get the page title (16183ms)
  webdriver-http-sync:request GET http://127.0.0.1:4499/session/c884f140-b224-11e4-a842-255fd52ba2bf/url +16s null
    ✓ can get the url (16187ms)
```

That's 16 seconds for a simple get request. For comparison:

```
> time curl -XGET http://127.0.0.1:4499/session/2d6d7640-b225-11e4-a842-255fd52ba2bf/title
{"sessionId":"2d6d7640-b225-11e4-a842-255fd52ba2bf","status":0,"value":"A title"}curl -XGET   0.00s user 0.00s system 82% cpu 0.007 total
```

Yes, that's 7ms total time.
